api_version = "2025-04"

[[extensions]]
name = "phoenix-automatic-discount"
handle = "phoenix-automatic-discount"

uid = "06c41050-a6d4-b524-38fd-4563ed708ee61752ebef"

type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
  export = "cart-delivery-options-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.input.variables]
  namespace = "phoenix-automatic-discount"
  key = "function-configuration"
